# Aplicamos las configuraciones que usabamos por línea de comandos
# pero la diferencia es que esta vez está condensando en un solo comando.
services:
  # Primero la base de datos
  yarah-db-ms-professors:
    image: postgres:16.4
    container_name: yarah-db-ms-professors
    ports:
      - "5558:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: yarah_ms_professors_db
      POSTGRES_USER: postgres
    volumes:
      - data-ms-professors:/var/lib/postgresql/data
    networks:
      - liceo_yarah

  # Ahora la aplicación, la aplicación depende primero de que la BD esté operando.
  # Con el build la idea es que se construya la imagen, para que sea en un solo comando.
  yarah-ms-professors:
    container_name: yarah-ms-professors
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: liceoyarah-ms-professors-image
    ports:
      - "18884:18884"
    networks:
      - liceo_yarah
    depends_on:
      - yarah-db-ms-professors

# Por aparte debo dejar claramente definido los volumenes y la red
# NOTA 1 -> Debe existir el volumen si queremos re usar la información
# NOTA 2 -> La red tiene que estar creada con antelación para no tener problemas.
volumes:
  data-ms-professors:
    name: data-ms-professors
networks:
  liceo_yarah:
    name: liceo_yarah
    external: true




