apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarah-db-ms-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarah-db-ms-users
  template:
    metadata:
      labels:
        app: yarah-db-ms-users
    spec:
      containers:
      - image: postgres:16.4
        name: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "1234"
          - name: POSTGRES_DB
            value: yarah_ms_users_db
          - name: POSTGRES_USER
            value: postgres
        volumeMounts:
          - name: data-k8s-yarah-db-ms-users
            mountPath: /var/lib/postgresql/data
      #Para persistir los datos - Usamos el Claim para la reclamación
      volumes:
        - name: data-k8s-yarah-db-ms-users
          persistentVolumeClaim:
            claimName: ms-users-pvc.claim

---
#Para la conexión desde afuera
apiVersion: v1
kind: Service
metadata:
  name: yarah-db-ms-users
spec:
  selector:
    app: yarah-db-ms-users
  ports:
    - protocol: TCP
      port: 5432       # Puerto dentro del clúster
      targetPort: 5432 # Puerto dentro del contenedor
      nodePort: 30002  # Puerto expuesto externamente (escoge uno en el rango 30000-32767)
  type: NodePort       # Define que este servicio será de tipo NodePort
